before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: T1gLJIa4XZrDWf1XeLUrgXXI/x7Sk41oV4uvslPgZlNBFoqH6Ah/PKXnJaqW78P1Q0dDdfpKveU4BeRy/URgaLCUOBlFYxVy3TwZryxa5rMOEXdy/1SkQz1q3xluzUUWZzFcehmputLHZHG8jaUZfd0hsv4fYiWV/XKqNRjk7+MkEYgEnw882v2JNAgq6VjmOuMqX+4ach51E+NiyE4Y1GhJWHHCa06AjSJKR/PxcgCJ/DRlwinEAddpn0UBlm00BXQthTUGxJo2rUtRFWj69by+qRzUr3mmlXnV0kHr+x5ja+ss7H+7zvUugWE9kjJMHNK0Eh+n/I1D7SdMXmyWA1x0oCV05VHqkJ3G3sqcyctM/km5ZuGPkWakkcz54gS/yoBn0szYFL1JocfEDeLMtsloeru85pVHMvJ3/q6TV4LP2T7QjqWNpirye9n2Z9v3hLbMjqJ6aG6ozVoIZH5UGwXiuUPaXkQTzkjrr9SsGP2Trg8PSWuu/soGeOEMeWMsXz5dUx/8z49kVzGG+PuRaGlr531h1sUi6wDgXx5P4QFqaPTZHRU/RbXwbmHMuaV4/Dh7ITt5wVBGRVBvKpkR0ro2aHqmLGaSDp1edZjy9kPbUjDQOqAYy4AHPVVQkKZp8gcDcY1tKx/dNFbYOLQpN3qhjfpDEe15C/O3lOVJUXI= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
